package com.doctor.mybatisdemo.domain;

import java.util.Date;

public class applyType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.id
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.title
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.company_id
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.item_type
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Byte itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.status
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.content
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.loanable
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Byte loanable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.printable
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Byte printable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.cost_able
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Byte costAble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.relation_able
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Byte relationAble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.budget_able
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Byte budgetAble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.created_at
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.updated_at
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clb_apply_type.deleted_at
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.id
     *
     * @return the value of clb_apply_type.id
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.id
     *
     * @param id the value for clb_apply_type.id
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.title
     *
     * @return the value of clb_apply_type.title
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.title
     *
     * @param title the value for clb_apply_type.title
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.company_id
     *
     * @return the value of clb_apply_type.company_id
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.company_id
     *
     * @param companyId the value for clb_apply_type.company_id
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.item_type
     *
     * @return the value of clb_apply_type.item_type
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Byte getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.item_type
     *
     * @param itemType the value for clb_apply_type.item_type
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setItemType(Byte itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.status
     *
     * @return the value of clb_apply_type.status
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.status
     *
     * @param status the value for clb_apply_type.status
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.content
     *
     * @return the value of clb_apply_type.content
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.content
     *
     * @param content the value for clb_apply_type.content
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.loanable
     *
     * @return the value of clb_apply_type.loanable
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Byte getLoanable() {
        return loanable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.loanable
     *
     * @param loanable the value for clb_apply_type.loanable
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setLoanable(Byte loanable) {
        this.loanable = loanable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.printable
     *
     * @return the value of clb_apply_type.printable
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Byte getPrintable() {
        return printable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.printable
     *
     * @param printable the value for clb_apply_type.printable
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setPrintable(Byte printable) {
        this.printable = printable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.cost_able
     *
     * @return the value of clb_apply_type.cost_able
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Byte getCostAble() {
        return costAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.cost_able
     *
     * @param costAble the value for clb_apply_type.cost_able
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setCostAble(Byte costAble) {
        this.costAble = costAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.relation_able
     *
     * @return the value of clb_apply_type.relation_able
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Byte getRelationAble() {
        return relationAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.relation_able
     *
     * @param relationAble the value for clb_apply_type.relation_able
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setRelationAble(Byte relationAble) {
        this.relationAble = relationAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.budget_able
     *
     * @return the value of clb_apply_type.budget_able
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Byte getBudgetAble() {
        return budgetAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.budget_able
     *
     * @param budgetAble the value for clb_apply_type.budget_able
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setBudgetAble(Byte budgetAble) {
        this.budgetAble = budgetAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.created_at
     *
     * @return the value of clb_apply_type.created_at
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.created_at
     *
     * @param createdAt the value for clb_apply_type.created_at
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.updated_at
     *
     * @return the value of clb_apply_type.updated_at
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.updated_at
     *
     * @param updatedAt the value for clb_apply_type.updated_at
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clb_apply_type.deleted_at
     *
     * @return the value of clb_apply_type.deleted_at
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clb_apply_type.deleted_at
     *
     * @param deletedAt the value for clb_apply_type.deleted_at
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}