package com.doctor.mybatisdemo.dao;

import com.doctor.mybatisdemo.domain.applyType;

public interface applyTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clb_apply_type
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clb_apply_type
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    int insert(applyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clb_apply_type
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    int insertSelective(applyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clb_apply_type
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    applyType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clb_apply_type
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    int updateByPrimaryKeySelective(applyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clb_apply_type
     *
     * @mbggenerated Wed Mar 16 15:21:29 CST 2016
     */
    int updateByPrimaryKey(applyType record);
}